
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import static java.util.logging.Level.ALL;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ferpa
 */
public class Crear_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Crear_Producto
     */
    
    Inventario inve;
   int n=0,m=0,h=0,p=0;
    public String f="Selecciona Categoria";
    public Crear_Producto() {
        initComponents();
       
        this.lista1.removeAllItems();
        
        this.lista2.removeAllItems();
        this.tipo.removeAllItems();
        this.bodega.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        unidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pcantida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idP = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lista1 = new javax.swing.JComboBox();
        lista2 = new javax.swing.JComboBox();
        btnRegresar5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        bodega = new javax.swing.JComboBox<>();

        jLabel4.setText("Id Categoria:");

        unidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unidadKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre Producto:");

        Pcantida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PcantidaKeyTyped(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio Unidad:");

        idP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPFocusLost(evt);
            }
        });
        idP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idPKeyTyped(evt);
            }
        });

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        jLabel8.setText("Precio Por Cantidad:");

        jLabel2.setText("Id Producto:");

        jLabel3.setText("Id Ubicacion:");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Crear Producto");

        lista1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        lista1.setToolTipText("Seleccionar Categoria");
        lista1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lista1ItemStateChanged(evt);
            }
        });
        lista1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lista1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lista1FocusLost(evt);
            }
        });
        lista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista1MouseClicked(evt);
            }
        });
        lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista1ActionPerformed(evt);
            }
        });

        lista2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccionar", "Item 2", "Item 3", "Item 4" }));
        lista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista2ActionPerformed(evt);
            }
        });

        btnRegresar5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegresar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK2.png"))); // NOI18N
        btnRegresar5.setBorderPainted(false);
        btnRegresar5.setContentAreaFilled(false);
        btnRegresar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK3.png"))); // NOI18N
        btnRegresar5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK.png"))); // NOI18N
        btnRegresar5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegresar5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar5MouseClicked(evt);
            }
        });
        btnRegresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de compra:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel10.setText("Bodega");

        bodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodegaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lista2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idP, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(31, 31, 31)
                                                .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bodega, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Pcantida, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 89, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(Pcantida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(bodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar5)))
                .addContainerGap())
        );

        lista1.getAccessibleContext().setAccessibleName("Seleccionar Item");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista2ActionPerformed
        // TODO add your handling code here:
         //this.lista2.removeAllItems();
        
        
        
         try {
//lista2.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("{CALL seleccionarUbicacion()}");
            PreparedStatement Sentencia = miConexion.prepareStatement("{CALL llamarUbicacion(?)}");

        Sentencia.setString(1,(String)lista2.getSelectedItem());
        
         ResultSet rs =  miSentencia.executeQuery();
         ResultSet llamar=Sentencia.executeQuery();
         
         if(m==0){
         
         this.lista2.addItem("Selecciona una Opcion");
         
         }
         
         while(rs.next() && m==0){
             
             
             this.lista2.addItem(rs.getString(1));
         
             
         
         }
         m=1;
         
        
         

        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_lista2ActionPerformed

    
 
    
    private void lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista1ActionPerformed
       // TODO add your handling code here:
      
        
       try {

            
            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("{CALL seleccionarCategoria()}");
            PreparedStatement Sentencia = miConexion.prepareStatement("{CALL llamarCategoria(?)}");
        
          Sentencia.setString(1,(String)lista1.getSelectedItem());
          //miConexion.createStatement();
            ResultSet rs =  miSentencia.executeQuery();
            ResultSet llamar=Sentencia.executeQuery();
         
      
         
         if(n==0){
         
         this.lista1.addItem("Selecciona una Opcion");
         
         }
         
          
         
         while(rs.next()&& n==0){
             
             
             this.lista1.addItem(rs.getString(1)); 
         
         }
       
         n=1;
         
      
         
         
         
     
       
       
         
       
            
        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
       
        
     

        
    
    }//GEN-LAST:event_lista1ActionPerformed

    private void lista1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lista1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lista1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      int x=0;
        
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("{CALL ingresarProductosMarca(?,?,?,?,?,?,?,?,?)}");

        
         miSentencia.setString(1,idP.getText());
         miSentencia.setString(2, (String) lista1.getSelectedItem());
         miSentencia.setString(3,(String) lista2.getSelectedItem());
         miSentencia.setString(4,nombre.getText());
         miSentencia.setInt(5,x);
         miSentencia.setString(6,unidad.getText());
         miSentencia.setString(7,Pcantida.getText());
         miSentencia.setString(8,(String)tipo.getSelectedItem());
         miSentencia.setString(9,(String)bodega.getSelectedItem());
         miSentencia.executeUpdate();
         
         
         idP.setText("");
         nombre.setText("");
         lista1.setSelectedIndex(0);
         lista2.setSelectedIndex(0);
         nombre.setText("");
         //cantida.setText("");
         unidad.setText("");
         Pcantida.setText("");

        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
        inve.mostrar();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void idPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPKeyPressed
        // TODO add your handling code here:
        
        String tecla=KeyEvent.getKeyText(evt.getKeyCode());
      
        System.out.println(tecla);
      String x="";
       
        if (evt.getKeyCode()==evt.VK_TAB || evt.getKeyCode()==evt.VK_ENTER) {
            
            
             if (idP.getText().equals("")) {

        } else {

            try {
                Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
                System.out.println("conexion establecidad");
                PreparedStatement miSentencia = miConexion.prepareStatement("{CALL validarSeleccion(?)}");
                
                miSentencia.setString(1, idP.getText());

                ResultSet rs = miSentencia.executeQuery();

                while (rs.next()) {
                    x = rs.getString(1);
                    System.out.println(x);
                }

       
                if (x.equals("1")) {
                    JOptionPane.showMessageDialog(null, "El codigo ingresado ya existe.");
                    
                    idP.requestFocus();
                    

                } else {

                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        }
    
    }//GEN-LAST:event_idPKeyPressed

    private void idPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPFocusLost
        // TODO add your handling code here:
        String x="";
         if (idP.getText().equals("")) {

        } else {

            try {
                Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
                System.out.println("conexion establecidad");
                PreparedStatement miSentencia = miConexion.prepareStatement("{CALL validarSeleccion(?)}");
                
                miSentencia.setString(1, idP.getText());

                ResultSet rs = miSentencia.executeQuery();

                while (rs.next()) {
                    x = rs.getString(1);
                    System.out.println(x);
                }

       
                if (x.equals("1")) {
                    JOptionPane.showMessageDialog(null, "El codigo ingresado ya existe.");
                    
                    idP.requestFocus();
                    

                } else {

                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_idPFocusLost

    private void lista1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lista1FocusLost
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_lista1FocusLost

    private void lista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista1MouseClicked
        // TODO add your handling code here:
       
        
        
        
    }//GEN-LAST:event_lista1MouseClicked

    private void lista1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lista1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lista1FocusGained

    private void btnRegresar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar5MouseClicked

    private void btnRegresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar5ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        inve.mostrar();
        
    }//GEN-LAST:event_btnRegresar5ActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
        
        try {
//lista2.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("{CALL llamarTipo()}");
            //PreparedStatement Sentencia = miConexion.prepareStatement("{CALL llamarUbicacion(?)}");

        //Sentencia.setString(1,(String)pago.getSelectedItem());
        
         ResultSet rs =  miSentencia.executeQuery();
         //ResultSet llamar=Sentencia.executeQuery();
         
         if(h==0){
         
         this.tipo.addItem("Selecciona una Opcion");
         
         }
         
         while(rs.next() && h==0){
             
             
             this.tipo.addItem(rs.getString(1));
         
             
         
         }
         h=1;
         
        
         

        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tipoActionPerformed

    private void bodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodegaActionPerformed
        // TODO add your handling code here:
        
        try {
//lista2.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("{CALL llamarbodega()}");
            //PreparedStatement Sentencia = miConexion.prepareStatement("{CALL llamarUbicacion(?)}");

        //Sentencia.setString(1,(String)pago.getSelectedItem());
        
         ResultSet rs =  miSentencia.executeQuery();
         //ResultSet llamar=Sentencia.executeQuery();
         
         if(p==0){
         
         this.bodega.addItem("Selecciona una Opcion");
         
         }
         
         while(rs.next() && p==0){
             
             
             this.bodega.addItem(rs.getString(1));
         
             
         
         }
         p=1;
         
        
         

        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bodegaActionPerformed

    private void idPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
               
          } 
    }//GEN-LAST:event_idPKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
               
          } 
    }//GEN-LAST:event_nombreKeyTyped

    private void PcantidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PcantidaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
               
          } 
    }//GEN-LAST:event_PcantidaKeyTyped

    private void unidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
               
          } 
    }//GEN-LAST:event_unidadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pcantida;
    private javax.swing.JComboBox<String> bodega;
    private javax.swing.JButton btnRegresar5;
    private javax.swing.JTextField idP;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox lista1;
    private javax.swing.JComboBox lista2;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables
}
