
import javax.swing.JFrame;
import java.util.Date;
import java.text.SimpleDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FAMILIA ROMA
 */
public  class Principal extends javax.swing.JFrame {

    VentanaProveedor objVentanaProveedor;
    VentanaVentas objVentanaVentas;
    IngresarCliente objCliente;
    mostrarClientes mostrarCliente;
    Inventario inventario;
    MostrarInventario p;
    compra objcompra;
    tabla ts;
    
    compra pago;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        labelFecha.setText(fecha());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botoni = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        labelFecha = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/A2.png"))); // NOI18N
        jButton1.setMnemonic('V');
        jButton1.setText("VENTAS");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(-3);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/A3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/A.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/B2.png"))); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("COMPRAS");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/B3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/B.png"))); // NOI18N
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/C2.png"))); // NOI18N
        jButton3.setMnemonic('P');
        jButton3.setText("PROVEEDORES");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/C3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/C.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton3KeyTyped(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/S2.png"))); // NOI18N
        jButton4.setText("   SALIR");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/S3.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/S.png"))); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        botoni.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        botoni.setForeground(new java.awt.Color(255, 255, 255));
        botoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/I2.png"))); // NOI18N
        botoni.setText("INVENTARIO");
        botoni.setBorder(null);
        botoni.setBorderPainted(false);
        botoni.setContentAreaFilled(false);
        botoni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botoni.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/I3.png"))); // NOI18N
        botoni.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/I.png"))); // NOI18N
        botoni.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoniActionPerformed(evt);
            }
        });

        Clientes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gente.png"))); // NOI18N
        Clientes.setText("CLIENTES");
        Clientes.setToolTipText("");
        Clientes.setBorder(null);
        Clientes.setBorderPainted(false);
        Clientes.setContentAreaFilled(false);
        Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clientes.setPreferredSize(new java.awt.Dimension(129, 153));
        Clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ClientesMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClientesMouseMoved(evt);
            }
        });
        Clientes.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ClientesMouseWheelMoved(evt);
            }
        });
        Clientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                ClientesComponentHidden(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });

        labelFecha.setBackground(new java.awt.Color(153, 153, 153));
        labelFecha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(153, 153, 153));
        labelFecha.setText("dd/mm/yyyy");

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Escritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(botoni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(Clientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(labelFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelFecha)
                .addGap(28, 28, 28)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(botoni))
                .addGap(71, 71, 71)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(jButton4))
                        .addGroup(EscritorioLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jButton3)))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton5)))
                .addGap(67, 67, 67))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscritorioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton1))
                            .addComponent(jButton3)))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton2)))
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton5)
                        .addGap(25, 25, 25)
                        .addComponent(jButton4))
                    .addComponent(botoni)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 876, 545));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (objVentanaVentas==null || objVentanaVentas.isClosed()) 
        {
         objVentanaVentas=new VentanaVentas();
         Escritorio.add(objVentanaVentas);
         objVentanaVentas.show();
         objVentanaVentas.setVisible(true);
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
            if (objVentanaProveedor==null || objVentanaProveedor.isClosed()) 
        {
            objVentanaProveedor=new VentanaProveedor();
            Escritorio.add(objVentanaProveedor);
            
            objVentanaProveedor.setVisible(true);
            objVentanaProveedor.show();
            objVentanaProveedor.setLocked(true);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyTyped

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        if (mostrarCliente==null || mostrarCliente.isClosed())
        {
            mostrarCliente=new mostrarClientes();
            Escritorio.add(mostrarCliente);

            mostrarCliente.setVisible(true);
            mostrarCliente.show();
           
            
           

        }

    }//GEN-LAST:event_ClientesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(pago==null || pago.isClosed()){
        
        pago = new compra();
        
        Escritorio.add(pago);
        pago.show();
        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesMouseMoved

    private void ClientesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesMouseDragged

    private void ClientesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ClientesMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesMouseWheelMoved

    private void ClientesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ClientesComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesComponentHidden

    private void botoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoniActionPerformed
     
        // TODO add your handling code here:
        
        if(inventario==null || inventario.isClosed()){
        
        inventario=new Inventario();
        Escritorio.add(inventario);
        inventario.setVisible(true);
        inventario.show();
        
        }
        
        
    }//GEN-LAST:event_botoniActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        if(ts==null || ts.isClosed()){
        
            ts=new tabla();
            Escritorio.add(ts);
            ts.show();
        
        
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
               
            
            }
             
            
        });
        
       
    }
    
    public static String fecha(){
        Date fecha=new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientes;
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton botoni;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel labelFecha;
    // End of variables declaration//GEN-END:variables
}
