
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author FAMILIA ROMA
 */
public class VentanaCrearProveedor extends javax.swing.JInternalFrame {

    public String x;
    VentanaProveedor objVentanaProveedor;
    VentanaCrearProveedor objVentanaCrearProveedor;
    bloquearVentana bloquear = new bloquearVentana();

    private boolean locked;

    /**
     * Creates new form VentanaCrearProveedor
     */
    @Override
    public void reshape(int x, int y, int width, int height) {
        if (!locked) {                                      //Este metodo me permite bloquear la VentanaCrearProveedor
            super.reshape(x, y, width, height);
        }
    }

    public boolean getLocked() {
        return locked;
    }
    //se crean los metodos para modificar el bloquea de VentanaCrearProveedor

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    /**
     * Creates new form VentanaCrearProveedor
     */
    /**
     * Creates new form VentanaEventoCrearProveedor
     */
    public VentanaCrearProveedor() {
        initComponents();
        this.setLocation(88, 50);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        bloquear.setLocked(true);
        cajaCodigo.requestFocus();
        cajonNotas.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cajaUrl = new javax.swing.JTextField();
        cajaTel = new javax.swing.JTextField();
        cajaRazon = new javax.swing.JTextField();
        comboDiaEntrega = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cajaFax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cajaEmail = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajonNotas = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        cajaPostal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cajaContactoVende = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboPais1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaDireccion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnModificar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(717, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 680, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Dia Entrega:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Razon Social:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Fax:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));
        jPanel1.add(cajaUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 190, -1));

        cajaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelActionPerformed(evt);
            }
        });
        jPanel1.add(cajaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 110, -1));

        cajaRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaRazonActionPerformed(evt);
            }
        });
        jPanel1.add(cajaRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 250, -1));

        comboDiaEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboDiaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 40, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Ciudad:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        comboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Pagina Web:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel1.add(cajaFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Notas:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 50, -1));
        jPanel1.add(cajaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 250, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 250, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Email:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 120, 80, -1));

        cajonNotas.setColumns(20);
        cajonNotas.setRows(5);
        jScrollPane1.setViewportView(cajonNotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 210, 130));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("C.Postal:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 80, -1));
        jPanel1.add(cajaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 120, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_user.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 165, 70));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/button_cancel.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setMaximumSize(new java.awt.Dimension(149, 25));
        btnCancelar.setMinimumSize(new java.awt.Dimension(149, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 165, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Contacto Vendedor:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(cajaContactoVende, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 190, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Pais:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        comboPais1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboPais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cajaCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaCodigoFocusLost(evt);
            }
        });
        cajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodigoActionPerformed(evt);
            }
        });
        cajaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(cajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 30, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 60, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Nit:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cajaNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNitActionPerformed(evt);
            }
        });
        jPanel1.add(cajaNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Dirección:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cajaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(cajaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 120, 110, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, 680, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 10, 300));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 10, 300));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ok-icon.png"))); // NOI18N
        btnModificar.setText("ACEPTAR CAMBIOS");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 165, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaRazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaRazonActionPerformed

    private void cajaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDireccionActionPerformed

    private void cajaNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNitActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodigoActionPerformed
      
        
        
        //cajaNombre.requestFocus();

       
    }//GEN-LAST:event_cajaCodigoActionPerformed

    private void cajaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (objVentanaProveedor == null || objVentanaProveedor.isClosed()) {

            objVentanaProveedor = new VentanaProveedor();
            Principal.Escritorio.add(objVentanaProveedor);
            objVentanaProveedor.show();
            objVentanaProveedor.setLocked(true);
        }
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int flag = 0;

        if (cajaCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "El campo Codigo esta vacio");
            cajaCodigo.requestFocus();
        } else {
            if (cajaNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "El campo Nombre esta vacio");
                cajaNombre.requestFocus();
            } else {
                if (cajaNit.getText().equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "El campo Nit esta vacio");
                    cajaNit.requestFocus();
                } else {
                    if (cajaDireccion.getText().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "El campo Direccion esta vacio");
                        cajaDireccion.requestFocus();
                    } else {
                        if (cajaRazon.getText().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "El campo Razon Social esta vacio");
                            cajaRazon.requestFocus();
                        } else {
                            if (comboPais1.getSelectedItem().toString().equals("Seleccionar")) {
                                JOptionPane.showMessageDialog(rootPane, "Seleccion un Pais");
                                comboPais1.requestFocus();
                            } else {
                                 if (comboCiudad.getSelectedItem().toString().equals("Seleccionar")) {
                                        JOptionPane.showMessageDialog(rootPane, "Seleccione una Ciudad");
                                        comboCiudad.requestFocus();
                                    } 
                                else {
                                   flag=1;
                                 
                                }
                            }
                        }
                    }
                }
            }
            System.out.println(flag);

            if (flag == 1) {
                ingresarProveedor();
                JOptionPane.showMessageDialog(rootPane, "Registro Exitoso");

                if (objVentanaProveedor == null || objVentanaProveedor.isClosed()) {

                    objVentanaProveedor = new VentanaProveedor();
                    Principal.Escritorio.add(objVentanaProveedor);
                    objVentanaProveedor.show();
                    objVentanaProveedor.setLocked(true);
                }
                dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void cajaCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCodigoKeyTyped
        
        
    }//GEN-LAST:event_cajaCodigoKeyTyped

    private void cajaCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCodigoKeyPressed
       //char teclaPresionada=evt.getKeyChar();
        String tecla=KeyEvent.getKeyText(evt.getKeyCode());
      
        System.out.println(tecla);
      
       
        if (evt.getKeyCode()==evt.VK_TAB || evt.getKeyCode()==evt.VK_ENTER) {
            
            
             if (cajaCodigo.getText().equals("")) {

        } else {

            try {
                Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
                System.out.println("conexion establecidad");
                PreparedStatement miSentencia = miConexion.prepareStatement("{CALL validar_idProveedor(?)}");

                miSentencia.setString(1, cajaCodigo.getText());

                ResultSet rs = miSentencia.executeQuery();

                while (rs.next()) {
                    x = rs.getString(1);
                    System.out.println(x);
                }

                if (x.equals("1")) {
                    JOptionPane.showMessageDialog(null, "El codigo ingresado ya existe.");
                    cajaCodigo.requestFocus();

                } else {

                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        }
     
    }//GEN-LAST:event_cajaCodigoKeyPressed

    private void cajaCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaCodigoFocusLost
        // TODO add your handling code here:
        if (cajaCodigo.getText().equals("")) {

        } else {

            try {
                Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
                System.out.println("conexion establecidad");
                PreparedStatement miSentencia = miConexion.prepareStatement("{CALL validar_idProveedor(?)}");

                miSentencia.setString(1, cajaCodigo.getText());

                ResultSet rs = miSentencia.executeQuery();

                while (rs.next()) {
                    x = rs.getString(1);
                    System.out.println(x);
                }

                if (x.equals("1")) {
                    JOptionPane.showMessageDialog(null, "El codigo ingresado ya existe.");
                    cajaCodigo.requestFocus();

                } else {

                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cajaCodigoFocusLost

    public void ingresarProveedor() {
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
            System.out.println("conexion establecidad");
            PreparedStatement miSentencia = miConexion.prepareStatement("CALL insertar_proveedor(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            miSentencia.setString(1, cajaCodigo.getText());
            miSentencia.setString(2, cajaNombre.getText());
            miSentencia.setString(3, cajaRazon.getText());
            miSentencia.setString(4, cajaNit.getText());
            miSentencia.setString(5, cajaDireccion.getText());
            miSentencia.setString(6, comboCiudad.getSelectedItem().toString());
            miSentencia.setString(7, cajaPostal.getText());
            miSentencia.setString(8, comboPais1.getSelectedItem().toString());
            miSentencia.setString(9, cajaEmail.getText());
            miSentencia.setString(10, cajaFax.getText());
            miSentencia.setString(11, cajaTel.getText());
            miSentencia.setString(12, cajaContactoVende.getText());
            miSentencia.setString(13, cajaUrl.getText());
            miSentencia.setString(14, comboDiaEntrega.getSelectedItem().toString());
            miSentencia.setString(15, cajonNotas.getSelectedText());
            miSentencia.executeUpdate();

        } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnModificar;
    public static javax.swing.JTextField cajaCodigo;
    public static javax.swing.JTextField cajaContactoVende;
    public static javax.swing.JTextField cajaDireccion;
    public static javax.swing.JTextField cajaEmail;
    public static javax.swing.JTextField cajaFax;
    public static javax.swing.JTextField cajaNit;
    public static javax.swing.JTextField cajaNombre;
    public static javax.swing.JTextField cajaPostal;
    public static javax.swing.JTextField cajaRazon;
    public static javax.swing.JTextField cajaTel;
    public static javax.swing.JTextField cajaUrl;
    public static javax.swing.JTextArea cajonNotas;
    public static javax.swing.JComboBox<String> comboCiudad;
    public static javax.swing.JComboBox<String> comboDiaEntrega;
    public static javax.swing.JComboBox<String> comboPais1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables
}
