
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FAMILIA ROMA
 */
public class VentanaProveedor extends javax.swing.JInternalFrame {
    VentanaCrearProveedor objVentanaCrearProveedor;
   
     private boolean locked ;
    
    /**
     * Creates new form VentanaCrearProveedor
     */
    @Override
    public void reshape(int x, int y, int width, int height) 
    {
        if (!locked) {                                      //Este metodo me permite bloquear la VentanaCrearProveedor
        super.reshape(x, y, width, height);
        }
    }

    public boolean getLocked()
    {                                              
        return locked;
    }
                                                     //se crean los metodos para modificar el bloquea de VentanaCrearProveedor
    public void setLocked(boolean locked) 
    {
        this.locked = locked;
    }
    
    
    
    
    public VentanaProveedor() {
        initComponents();
        this.setLocation(88, 50);
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
            mostrarTabla();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnRegresar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(717, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK2.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK3.png"))); // NOI18N
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK.png"))); // NOI18N
        btnRegresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 322, 69, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("CREAR PROVEEDOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 60));

        jTable2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setRowHeight(20);
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 45, 558, 209));

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(720, 469));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK2.png"))); // NOI18N
        btnRegresar1.setBorderPainted(false);
        btnRegresar1.setContentAreaFilled(false);
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK3.png"))); // NOI18N
        btnRegresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BACK.png"))); // NOI18N
        btnRegresar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegresar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseClicked(evt);
            }
        });
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 322, 69, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("CREAR PROVEEDOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 322, -1, 60));

        jTable3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable3.setRowHeight(20);
        jScrollPane2.setViewportView(jTable3);

        jInternalFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 45, 558, 209));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        jButton3.setText("MODIFICAR PROVEEDOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
       
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
       
       if (objVentanaCrearProveedor==null || objVentanaCrearProveedor.isClosed()) 
        {
            objVentanaCrearProveedor=new VentanaCrearProveedor();
            Principal.Escritorio.add(objVentanaCrearProveedor);
            
           objVentanaCrearProveedor.setVisible(true);
            objVentanaCrearProveedor.show();
            objVentanaCrearProveedor.setLocked(true);
            VentanaCrearProveedor.btnModificar.setVisible(false);
            
           this.dispose();
        }
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar1MouseClicked

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable2.getSelectedRow()>=0) 
        {
         if (objVentanaCrearProveedor==null || objVentanaCrearProveedor.isClosed()) 
         {
            objVentanaCrearProveedor=new VentanaCrearProveedor();
            Principal.Escritorio.add(objVentanaCrearProveedor);
            
           objVentanaCrearProveedor.setVisible(true);
            objVentanaCrearProveedor.show();
            objVentanaCrearProveedor.setLocked(true);
            VentanaCrearProveedor.btnGuardar.setVisible(false);
            VentanaCrearProveedor.jPanel1.setLayout(null);
            VentanaCrearProveedor.btnModificar.setBounds(180, 350, 165, 70);
            
           this.dispose();
         }
         
         int fila= jTable2.getSelectedRow();
         
         if (fila>=0) 
         {
             try {
           Connection miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/sipe", "root", "");
             System.out.println("conexion establecidad");
            PreparedStatement miSentencia=miConexion.prepareStatement("SELECT * FROM PROVEEDORES WHERE idProveedor=?");
            
                
                 
             miSentencia.setString(1, jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
             
             
             ResultSet rs=miSentencia.executeQuery();
             
             while (rs.next()) {
                 VentanaCrearProveedor.cajaCodigo.setText(rs.getString(1));
                 VentanaCrearProveedor.cajaCodigo.setEditable(false);
                 VentanaCrearProveedor.cajaNombre.setText(rs.getString(2));
                  VentanaCrearProveedor.cajaRazon.setText(rs.getString(3));
                   VentanaCrearProveedor.cajaNit.setText(rs.getString(4));
                    VentanaCrearProveedor.cajaDireccion.setText(rs.getString(5));
                     VentanaCrearProveedor.comboCiudad.setSelectedItem(rs.getString(6));
                      VentanaCrearProveedor.cajaPostal.setText(rs.getString(7));
                       VentanaCrearProveedor.comboPais1.setSelectedItem(rs.getString(8));
                        VentanaCrearProveedor.cajaEmail.setText(rs.getString(9));
                         VentanaCrearProveedor.cajaFax.setText(rs.getString(10));
                          VentanaCrearProveedor.cajaTel.setText(rs.getString(11));
                           VentanaCrearProveedor.cajaContactoVende.setText(rs.getString(12));
                            VentanaCrearProveedor.cajaUrl.setText(rs.getString(13));
                             VentanaCrearProveedor.comboDiaEntrega.setSelectedItem(rs.getString(14));
                              VentanaCrearProveedor.cajonNotas.append(rs.getString(15));
                             
             }
             
             }
             catch(SQLException se){
            se.printStackTrace();
        }
         }
      }else
        {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Proveedor");
        }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    public void mostrarTabla(){
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion=DriverManager.getConnection("jdbc:mysql://localhost/sipe", "root", "");
            Statement stm=conexion.createStatement();
            ResultSet rst=stm.executeQuery("CALL mostrar_vista_proveedores");
            ResultSetMetaData rsMd= rst.getMetaData();
            int numeroColumnas=rsMd.getColumnCount();
            
            DefaultTableModel modelo= new DefaultTableModel();
            this.jTable2.setModel(modelo);
            
                for (int x = 1; x <= numeroColumnas; x++) {
                 modelo.addColumn(rsMd.getColumnLabel(x));
            }
                
                while (rst.next()) {
                Object[]fila=new Object [numeroColumnas];
                
                    for (int y = 0; y < numeroColumnas; y++) {
                        fila[y]=rst.getObject(y+1);
                    }
                    modelo.addRow(fila);
                           
                }
            
            
         } catch (ClassNotFoundException ce) {
            ce.printStackTrace();
        } catch(SQLException se){
            se.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables

}
